<a href="https://colab.research.google.com/github/TriciaButler/MAT-494-Data-Science/blob/main/Tricia_B_HW_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tricia Butler HW 4.2
*   Incidence Matrix
*   Rayleigh Quotient 


In [11]:
# Incidence Matrix
import networkx as nx

nodes = [1, 2, 3, 4, 5, 6]
edges = [[1, 2], [1, 3], [1, 5], [2, 3], [2, 4], [3, 4], [3, 5], [4, 6], [5, 6]]

G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

incidence_matrix = -nx.incidence_matrix(G, oriented=True) 
print(incidence_matrix.toarray())

[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  1.  0.  0.  0.  0.]
 [ 0. -1.  0. -1.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.]]


In [12]:
# Rayleigh Quotient 
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)

def rayleigh_quotient(x,A):
    return(x.T.dot(A).dot(x)/x.T.dot(x))

A = np.random.randn(2,2)
A = A.T.dot(A)

l,X = np.linalg.eig(A)

print(A.dot(X))
print(X.dot(np.eye(2)*l))

rayleigh_quotient(X[:,1],A)

[[-1.29020049 -4.82739792]
 [ 1.06629199 -5.84109345]]
[[-1.29020049 -4.82739792]
 [ 1.06629199 -5.84109345]]


7.577739988681693