<a href="https://colab.research.google.com/github/TriciaButler/MAT-494-Data-Science/blob/main/Tricia_B_HW_1_4*.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tricia Butler HW 1.4

# Single Value Decomposition 


*   SVD factors a matrix into 3 matrices.  A = USV^T
*   Matrix U is a matrix of the orthonormal eigenvectors of AA^T.
*   Matrix S diagonal matrix of the singular values
*   Matrix V^T is a transposed matrix containing the orthonormal eigenvectors of A^TA.



In [ ]:
print("A = USV^T")
import numpy as np
from scipy.linalg import svd
print("Matrix A")
X = np.array([[3, 3, 2], [2,3,-2]])
print(X)
print("-"*40)
print("Perform SVD")
U, singular,V_transpose = svd(X)
# print different components
print("Matrix U")
print(U)
print("-"*40)
print("Singular Array")
print(singular)
print("-"*40)
print("Matrix V^T")
print(V_transpose)

A = USV^T
Matrix A
[[ 3  3  2]
 [ 2  3 -2]]
----------------------------------------
Perform SVD
Matrix U
[[-0.7815437 -0.6238505]
 [-0.6238505  0.7815437]]
----------------------------------------
Singular Array
[5.54801894 2.86696457]
----------------------------------------
Matrix V^T
[[-0.64749817 -0.7599438  -0.05684667]
 [-0.10759258  0.16501062 -0.9804057 ]
 [-0.75443354  0.62869461  0.18860838]]


# Low-Rank Matrix Approximations


*   SVD Gives the Best Low Rank Approximation

